# Enhanced RAG Pipeline - Docker Compose
# PanScience Innovations LLM Specialist Assignment

version: '3.8'

services:
  rag-pipeline:
    build: .
    container_name: enhanced-rag-pipeline
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LOG_LEVEL=INFO
      - MAX_FILE_SIZE=4194304
      - MAX_DOCUMENTS=25
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rag-network

  # Optional: Add Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: rag-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - rag-network

networks:
  rag-network:
    driver: bridge

# volumes:
#   redis_data:
